version: 2
jobs:
  build-test-lint:
    macos:
      xcode: "9.4.1"
    environment:
      - BUNDLE_PATH: vendor/bundle
      - LC_ALL: en_US.UTF-8
      - LANG: en_US.UTF-8
    shell: /bin/bash --login -eo pipefail
    steps:
      - checkout
      - run:
          name: Preboot simulator
          command: xcrun instruments -w "iPhone 6 (11.4) [" || true
      - run:
          name: Output ruby version
          command: ruby -v
      - run:
          name: Output environment variables
          command: env
      - restore_cache:
          key: circlev2-{{ checksum "Gemfile.lock" }}
      - run:
          name: Install required gems
          command: bundle install
      - save_cache:
          key: circlev2-{{ checksum "Gemfile.lock" }}
          paths:
              - vendor/bundle
      - run:
          name: Build and run tests
          command: |
            xcodebuild \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGN_IDENTITY= \
            PROVISIONING_PROFILE= \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 6' \
            -workspace Astro.xcworkspace \
            -scheme "Astro" \
            clean build test |
            tee xcode_raw.log |
            xcpretty --color --report junit --output test_results.xml 
      - store_test_results:
          path: test_results.xml
      - store_artifacts:
          path: xcode_raw.log
      - run:
          name: Run danger
          command: bundle exec danger

workflows:
  version: 2
  build-test-lint:
    jobs:
      - build-test-lint:
          context: ios

